use crate::protocol::{
    ApiResponse, ImportPayload, KeyChord, ServerAction, ServerActionRequest,
    ServerCapabilitiesResponse, ServerCode,
};
use specta::TypeCollection;
use specta_typescript::{Exporter, Typescript};
use thiserror::Error;

const TYPESCRIPT_PREAMBLE: &str =
    "// This file has been generated by vibe-coding-remote-server. Do not edit this file manually.";

#[derive(Debug, Error)]
pub(super) enum RenderTypescriptError {
    #[error("failed to render TypeScript bindings: {0}")]
    Typescript(#[from] specta_typescript::Error),
}

pub(super) fn render_typescript_bindings() -> Result<String, RenderTypescriptError> {
    let types = TypeCollection::default()
        .register::<ApiResponse>()
        .register::<ImportPayload>()
        .register::<ServerCode>()
        .register::<ServerCapabilitiesResponse>()
        .register::<KeyChord>()
        .register::<ServerAction>()
        .register::<ServerActionRequest>();

    let bindings = Exporter::from(Typescript::default())
        .framework_prelude(TYPESCRIPT_PREAMBLE)
        .export(&types)?;

    Ok(preserve_server_code_alias(bindings))
}

fn preserve_server_code_alias(bindings: String) -> String {
    let bindings = bindings
        .replace("keys: string[]", "keys: ServerCode[]")
        .replace("supported_codes: string[]", "supported_codes: ServerCode[]");

    if bindings.contains("export type ServerCode = string;") {
        bindings
    } else {
        format!("{bindings}\nexport type ServerCode = string;\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exported_bindings_keep_the_server_code_alias() {
        let bindings = render_typescript_bindings().expect("bindings should render");

        assert!(bindings.contains("keys: ServerCode[]"));
        assert!(bindings.contains("supported_codes: ServerCode[]"));
        assert!(bindings.contains("export type ServerCode = string;"));
    }
}
